name: lint
on:
  pull_request:
jobs:
  lint:
    name: lint
    if: github.repository == 'SeldonIO/goven' # Do not run this on forks.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          skip-go-installation: true
