name: test
on:
  pull_request:
jobs:
  lint:
    name: test
    if: github.repository == 'SeldonIO/goven' # Do not run this on forks.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: test
        run: make test-coverage
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
